version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: ecr-sample
          tag: "$CIRCLE_SHA1"
